name = "Kelp"
uuid = "b4c0c025-ec9b-4767-a48c-4edf34c44f4a"
authors = ["Momme Butenschön"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
